# Generated by Django 3.0.3 on 2020-02-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_constructor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
