# Generated by Django 3.0.3 on 2020-02-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_constructor', '0002_auto_20200207_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
